version: "3.7"
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./pipelines:/opt/logstash/config/
      - ./logstash-conf:/etc/logstash/conf.d/
      - ./nginxlogs:/var/log/nginx
  nginx:
    image: nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginxlogs:/var/log/nginx